### ISSUE TITLE
Changing the Configuration at Runtime

### ISSUE THREAD

**Issue by dragos-rosca** [AxaGuilDEv/react-oidc#490]
I would like to change the configuration at runtime:

```javascript
const [someConvention, setSomeConvention] = useState();
const configuration = getConfiguration(someConvention);

return <AuthenticationProvider
            configuration={configuration}
            {...restOfProps}
        >
        {children}
        </AuthenticationProvider>
```

But because of how  `authenticationServiceInternal` in `authenticationService.ts` is made with that `if` at the beginning, new configurations will never be set.
```javascript
export const authenticationServiceInternal = (
  WebStorageStateStoreInt: typeof WebStorageStateStore
) => (configuration: UserManagerSettings, UserStore?: UserStoreType) => {
  if (userManager) {
    return userManager;
  }
[...]
```

Can you please instruct me on what is the proper way to change the configuration at runtime without having to access `setUserManager` and set it to `null`. The code doesn't seem to want that export being used by client developers .... I think. And it feels like a dirty workaround.
Maybe include a comparison in that `if` to see if the config is changed?

**Comment by guillaume-chervet** [comment]
Hi @dragos-rosca , thank you for your issue it is a good point to investigate. We are lacking of time this month. Have you tried to switch bettween multiple <AuthenticationProvider
            configuration={configuration}
            {...restOfProps}
        >
        {children}
        </AuthenticationProvider>

**Comment by dragos-rosca** [comment]
Sorry for the late reply. I will try to see if I can use multiple AuthentificationProviders, but I would also like to have an official way of changing the configuration. The `getConfiguration(someConvention)` part uses something from the oidcUser as `someConvention` (in this case a tenant).

**Comment by dragos-rosca** [comment]
Hello, so I tried using multiple `AuthenticationProvider`s (actually a normal JS function generating that node) and I'm having trouble with the events ... it seems I keep getting `authority mismatch on settings vs. signin state` like it starts authenticating on the old authority before I get the chance to change the config. 
Without setting the userManger to null it seems it's still used between renders and I can't change it in time.

I will still try to find a good way to use multiple `AuthenticationProvider`, but until I find a stable solution I'll go with `setUserManger(null)` and I will continue to monitor this issue for a better solution.

**Comment by guillaume-chervet** [comment]
It its a good think to be able to Change the configuration at runtime.

@oyouf, do you have time to investigate?

**Comment by guirenard59** [comment]
Hi, I'm adding a 👍  to that request.
Having to change the configuration is also a required feature on my side.

Thank you guys

**Comment by dragos-rosca** [comment]
I haven't forgotten about this. Please look into this!

**Comment by guillaume-chervet** [comment]
Yes, i would like to work on it. But i am lacking of time. Thank you for the message

**Comment by brunettia** [comment]
@dragos-rosca what is you current solution ?

**Comment by dragos-rosca** [comment]
Hello, so my current solution is to get pass that `if (userManager)` and for this I found `setUserManager` somewhere "hidden" in the library. But I don't think it was intended for use because for you to reach it you have to import it from a path inside the library:

```javascript
import { setUserManager } from '@axa-fr/react-oidc-core/dist/services/authenticationService'
```

And when I need to change the config I just set the `userManager` to `null` after I remove the user because it has a copy in session/local storage.

```javascript
      const userManager = getUserManager()
      await userManager.removeUser()

      setUserManager(null)
```

**Comment by dragos-rosca** [comment]
For a better understanding of my solution you can generate a React project with our generators [generator-webapp-rocket](https://github.com/osstotalsoft/generator-webapp-rocket) and look at the `TenantAuthenticationProvider.js`  (you need to choose multi-tenancy).
You can also see the code directly in the generator but it will have some template specific code [here is the file](https://github.com/osstotalsoft/generator-webapp-rocket/blob/master/generators/app/templates/infrastructure/src/providers/TenantAuthenticationProvider.js)

**Comment by brunettia** [comment]
I see, thank you !

**Comment by guillaume-chervet** [comment]
In v4 you can now authenticate to multiple providers https://www.npmjs.com/package/@axa-fr/react-oidc-context
I will add a case for your dynamic config change in the next patch. It will resolve your need if you still need it.

**Comment by dragos-rosca** [comment]
hello, thank you. I still need it. I will wait for your example! :)

**Comment by guillaume-chervet** [comment]
Does https://black-rock-0dc6b0d03-705.westeurope.1.azurestaticapps.net/multi-auth
temporary static web from pullrequest #705 seem to correspond to your needs? 
https://black-rock-0dc6b0d03-705.westeurope.1.azurestaticapps.net/multi-auth

**Comment by guillaume-chervet** [comment]
The actual demo version :
https://black-rock-0dc6b0d03.1.azurestaticapps.net/

**Comment by dragos-rosca** [comment]
Hello, 
Thank you for the demo. 
I'm sorry I didn't have the time to respond or to check if the code works in my case.
As soon as I get some time I'll test it in my use case (with multi-tenancy):
-  [generator-webapp-rocket](https://github.com/osstotalsoft/generator-webapp-rocket)
-  [here is the file](https://github.com/osstotalsoft/generator-webapp-rocket/blob/master/generators/app/templates/infrastructure/src/providers/TenantAuthenticationProvider.js)

But from what I see it should work. My use case just modifies the `acr_values` while you are logged in and it should keep you logged in, or at least you should have new `acr_values` in your config.

Have a nice day!

**Comment by guillaume-chervet** [comment]
Hi @dragos-rosca , thank you for your issue. I close it, I think v5 resolve your use case. Feel free to reopen it if you need it.

**Comment by dragos-rosca** [comment]
Hello,
Sorry for making you wait for so long.

I have finally tried to update my code to use the version `5.4.2` library and I have some problems.
When I change the configuration, nothing happens and I need to wait for the next token refresh to see the change in my `access token`.
Then I put a little bit of code to `refreshTokensAsync()` and (going over the fact that I had to use workarounds like importing from `@axa-fr/react-oidc-context/dist/vanilla`) I still have a big problem. After I manually refresh the token I do get a new access token in my `Session Storage` but, because the library only exposes ways to read the tokens from a local constant `const oidcDatabase = {};` that is not up to date, I still get the old access token.

I have a few functionalities missing because I have to use the access token outside React components and `getUserManager` no longer exists, but I figured that will come with `@axa-fr/vanilla-oidc`.

**Comment by dragos-rosca** [comment]
I don't think I can reopen the issue on my own.
If you need me to make a new issue please let me know or please reopen this one.

**Comment by guillaume-chervet** [comment]
Do you have a sample of code of wht you zre trying to do?

**Comment by dragos-rosca** [comment]
Hello,
I have a hard time sharing code in a sand box because there are 3 projects that need to go up (React + Apollo frontend, Nodejs GQL backend and the Identity server dotnet core).

So here is an attempt at putting here the important part. If it's not enough I will try to make a sand box because we don't need to involve GQL right now. I can show you that the token in `oidcDatabase` is not the same as the token in the session storage.

Here we have the configuration function. The important part is the `acr_values` that value dictates a property inside the access token. Based on the `acr_values` the Identity server sets `tid` (tenant id) inside the token
```javascript
const root = `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}`
const AUTH = {
  CALLBACK: '/authentication/callback',
  SILENT_CALLBACK: '/authentication/silent_callback'
}

const getAuthenticationConfiguration = tenant => {
  const acr_values = isNullOrWhitespace(tenant) ? undefined : `tenant:${tenant}`
  return {
    client_id: env.REACT_APP_IDENTITY_CLIENT_ID,
    authority: env.REACT_APP_IDENTITY_AUTHORITY,
    redirect_uri: `${root}${AUTH.CALLBACK}`,
    silent_redirect_uri: `${root}${AUTH.SILENT_CALLBACK}`,
    scope: 'openid profile ' + env.REACT_APP_IDENTITY_SCOPE,
    register_uri: `${env.REACT_APP_IDENTITY_AUTHORITY}/${env.REACT_APP_REGISTER_REDIRECT_URL}?returnUrl=${root}/register&clientId=${env.REACT_APP_IDENTITY_CLIENT_ID}`,
    extras: {
      response_type: 'code',
      post_logout_redirect_uri: `${root}`,
      loadUserInfo: true,
      automaticSilentRenew: true,
      revokeAccessTokenOnSignout: true,
      triggerAuthFlow: true,
      acr_values
    }
  }
}

export default getAuthenticationConfiguration
```

Here is my authentication wrapper. I create a state that is connected to the session storage. From here we expose a method available for the whole project that can change the `tenant` value. When this value is change, we get a new `acr_values` in our configuration that will dictate the value of the `tid` in our token.
```javascript
import { Oidc } from '@axa-fr/react-oidc-context/dist/vanilla'

export const useSessionStorage = key => {
  const [state, setState] = useState(window.sessionStorage.getItem(key))
  useEffect(() => {
    state ? window.sessionStorage.setItem(key, state) : window.sessionStorage.removeItem(key)
  }, [key, state])

  return [state, setState]
}

export const TenantContext = createContext()
const TenantAuthenticationProvider = props => {
  const { children } = props
  const [tenant, setTenant] = useSessionStorage('tid')

// First Problem:
// I have to force this "refreshTokensAsync()" to get a synchronization between this tenant and the value in the token.
// If this is missing, the synchronization will happen at the next token refresh (when it will expire)
// But this synchronization will happen only in the session storage
  useEffect(() => {
    if (!tenant) return

    const oidc = Oidc.get()
    if (!oidc?.userInfo) return

    if (oidc.userInfo.tid !== tenant) oidc.refreshTokensAsync()
    console.log(oidc)
  }, [tenant])

  const setTenantCallback = useCallback(
    async e => {
      if ((!e && !tenant) || `${e}`.toUpperCase() === `${tenant}`.toUpperCase()) {
        return
      }

      setTenant(e)
    },
    [setTenant, tenant]
  )

  const configuration = getAuthenticationConfiguration(tenant)

  return (
    <TenantContext.Provider value={setTenantCallback}>
      <OidcProvider
        configuration={configuration}
        authenticating={Authenticating}
        callbackSuccessComponent={CallbackPage}
        loadingComponent={NotAuthenticated}
        sessionLostComponent={SessionExpired}
        callbackErrorComponent={Forbidden}
      >
        {children}
      </OidcProvider>
    </TenantContext.Provider>
  )
}

TenantAuthenticationProvider.propTypes = { children: PropTypes.element.isRequired }

export default TenantAuthenticationProvider
```

And now to show the difference on screen
```javascript
import React, { Fragment, useCallback, useState } from 'react'
import { Hidden, Typography } from '@material-ui/core'
import { useOidcAccessToken } from '@axa-fr/react-oidc-context'
import { Button } from '@bit/totalsoft_oss.react-mui.kit.core'

function parseJwt(token) {
  const base64Url = token.split('.')[1]
  const base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/')
  const jsonPayload = decodeURIComponent(
    atob(base64)
      .split('')
      .map(function (c) {
        return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2)
      })
      .join('')
  )

  return JSON.parse(jsonPayload)
}

function PrivacySettings() {
  const [refresh, setRefresh] = useState(false)
  const handleClick = useCallback(() => {
    setRefresh(r => !r)
  }, [])

  const oidcTokens = useOidcAccessToken()
  const sessionTokens = JSON.parse(sessionStorage.getItem('default'))?.tokens

  return (
    <Fragment>
      <Button onClick={handleClick}>Manually refresh session storage readout</Button>
      <Hidden>{refresh}</Hidden>
      <Typography variant='h5'>This is the token from &quot;useOidcAccessToken()&quot;</Typography>
      {oidcTokens && <Typography color='primary'>{JSON.stringify(parseJwt(oidcTokens.accessToken))}</Typography>}
      <hr />
      <Typography variant='h5'>This is the token from &quot;sessionStorage.getItem(&apos;default&apos;)&quot;</Typography>
      {sessionTokens && <Typography color='error'>{JSON.stringify(parseJwt(sessionTokens.accessToken))}</Typography>}
    </Fragment>
  )
}

export default PrivacySettings
```

And now for some step by step pictures.
When I first login everything is good
![image](https://user-images.githubusercontent.com/26022019/166895966-74078c37-592f-47f9-8db7-2547e75b7b63.png)

Now lets change the tenant and reread the session storage token
![image](https://user-images.githubusercontent.com/26022019/166896400-5b01e74f-d139-48bc-a862-a6ff8e7751d4.png)

The labels on the left are the names from the session storage that dictates the `acr_values` they are not taken from the token.

Hope this helps and if it doesn't I will try to see if I can make a sand box for you to test.

Thank you for helping me and have a great day!

**Comment by guillaume-chervet** [comment]
Thank you very much @dragos-rosca for the all the rich details , I will try to look out your case tomorrow (when i will be less tired :p)
I think I will have to bring you a new method or something else for your use case.

**Comment by guillaume-chervet** [comment]
Does version https://github.com/AxaGuilDEv/react-oidc/pull/778 answer to your need?
you can try 5.8.0-alpha0 version
I have a lot of clean up of code to do but it is functionnal in the pullrequest demo.

**Comment by guillaume-chervet** [comment]
https://black-rock-0dc6b0d03-778.westeurope.1.azurestaticapps.net/multi-auth

**Comment by dragos-rosca** [comment]
Hello,
I tried the new alpha version and I have a problem. It seems that I don't have a `refresh_token` and that makes the whole thing fall apart.
I don't get any errors, but because of that missing `refresh_token`, the `renewToken` does nothing in my code.

**Comment by guillaume-chervet** [comment]
Did you use the new method

renewTokens 

Build for yoy

**Comment by dragos-rosca** [comment]
Sorry, a bug in my chrome dev tools.

It skips the `if` entirely:
![image](https://user-images.githubusercontent.com/26022019/167420233-df492a7a-1df3-4671-89dd-bdc8349fe99e.png)

**Comment by guillaume-chervet** [comment]
You need to add scope
offline_access
To get the refesh token to the client

**Comment by dragos-rosca** [comment]
Hello,
I managed to activate the `offline_access` scope but I won't be able to keep it. The Identity Server team told me that they will not allow it in production. We use the iFrames with silent login flow.

With that out of the way, I did manage to use `offline_access` locally but the `renewTokensAsync()` didn't work. I do get new `nbf` and `exp` but my `tid` does not change. And this time it doesn't change even when token expires and it doesn't change in session storage either.

After some digging in your code I realized that me using the `refreshTokensAsync()` method is not a good idea because this method returns the tokens that need to go inside the `oidcDatabase` object and I don't even read the return.
I tried a bunch of stuff and combinations but to no avail.

We just need a better synchronization between the tokens in the session storage and the ones in the `oidDatabase`.

**Comment by dragos-rosca** [comment]
I'm from Romania. I'm only one hour difference from France, so we can have a team call when ever you can.
My teams email is `drosca@totalsoft.ro`

**Comment by guillaume-chervet** [comment]
hi @dragos-rosca , Iam very sorry for the delay. I think I have done all refacto that allow to resolve your use case (few dev left). I'am available if you want to discuss. my email: guillaume.chervet@axa.fr

**Comment by dragos-rosca** [comment]
Hello, I will try to make a demo as soon as possible and let you know if it's fixed now.

**Comment by dragos-rosca** [comment]
Hello,

So I started a brand new `create-react-app` project to only implement the configuration change.
I discovered that I wasn't using the `configurationName` and that was complicating things for me. I used the `configurationName` properly and everything worked like a charm, until the silent login.
On silent login for some reason I lose the `extra` part of the configuration and that loses the data I needed.


![s1](https://user-images.githubusercontent.com/26022019/188893931-cba82fd7-5deb-4062-959e-3b976b352f59.png)

As you can see in the `Watch` section the `href` only has `prompt=none` and no `acr_values`. This makes my identity server to fall back on the default tenant.
I think I'm missing the information on how to configure the `extras` when a silent login is triggered.

**Comment by guillaume-chervet** [comment]
Thank you @dragos-rosca  for the feeback. Very sorry for the delay I haven't seen your reply. I am not sure but i think i fixed that in the last version.
I will check this afternoon, it will be a missed property to reinject!

**Comment by dragos-rosca** [comment]
Hello and a happy new year!

I checked the latest version `6.11.3` and on silent login the extras are taken from the wrong place. There is nothing in the query parameters parsed from location `window.location.href`. The configuration name is correct and that configuration has the `extras` I set at the beginning but they are not present in the place where `SilentLogin` checks.

I'm still missing my extras after each silent login. The extras are present in the config at initiation and are seen in the `Nework` tab on the `Authorization` call, but as soon as I get to a silent login, my extras are gone, even if I don't change the OidcConfiguration.

Please help!

Kind regards,
Dragos Rosca

**Comment by guillaume-chervet** [comment]
hi @dragos-rosca ,

thank you very much to keep your help :)
I'am currently working on it related to #928

I may add some breaking change to make it work properly and I'am refactoring a litle bit t make it work in a clean way #930

**Comment by guillaume-chervet** [comment]
hi @dragos-rosca ,

It is working in the last version :)
I'am waiting for your feedback ^^

**Comment by dragos-rosca** [comment]
hello,

just updated to `6.13.0` and now my extras are missing even in the first call. The extras are totally ignored now.
Is there a new way to configure extras in the OIDC configurations?

**Comment by guillaume-chervet** [comment]
Hi @dragos-rosca,

Verry sorry, version @axa-fr/react-oidc@6.13.1 fixe that.
Thank you for your feedback.

for a sample look at :
[with extras](https://github.com/AxaGuilDEv/react-oidc/blob/e2f568e3ccd295e76095542b455a3325dd68e237/packages/react/src/MultiAuth.tsx#L42)

**Comment by dragos-rosca** [comment]
works like a charm. thank you for your dedication and for sticking with me this much!

Have a great day!

**Comment by guillaume-chervet** [comment]
Thank you @dragos-rosca for all your help an patience :)
